# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
dist: trusty

# https://docs.travis-ci.com/user/encryption-keys/
env:
  global:
    # RAYGUN_USERNAME
    - secure: "F+G6JgvLfvXjSmbDrV7VWefMbAD1qaA3aSIRF2OIwJMa9h6h4F3jYaX7w3+5BVBZnoMwl7XJC7tL732aIN4rr7l+VgAB8YjAzwbnTk19LS2/g4DrIBz6GVfBOFQtG9gMtpdJJmW8Xo3bDBuOXrGE2dZipz0E46NrHIp7JtEmqnv2DSLD0RwuCS+KMwtKzO8j9ZePrdNB66IxF/hPAeHOcyQg9t/7+szxXzX58rvqjVdgbLWyt16ZoVgNInuOrECricBJ8k7A5NzCjunvOsSE3YnNe86FRycpQd+XLvozqq3ZGvwuWKHzx6PfnqEEPKVNRun9deiv08BvTVxaqr4bK8pDMZEtqlL83WQcucB1uR+ldOYnG/DVfjgoGJ5kVmEyuUJu4CwTP1GkG0+vl/Bezkvzwt00k2d22x2jdKcdICAfzSXi2cz2SqeSSxF+L4n7Eml+G8a0NyIi/ZzVLQvaW4uZc+AK+Skz2q1HCp3POU0rX9I3cQKvq703oBRmkZjZLO16gySW9DMnlwIqDrIDOAYKG8ETwYIRPqm0juwAC7WkRgGJK+DWDwv2EEJbSD1urUMRUiuJkcXa8fWTPHV5/tA89JRsAqrgYPh+u6GjV9P00u/3boZqnMDPMtPUZVxfKUjcWA0HimfvP/Z+98i40Pg2GF6yUlpy1pMypfrp5jI="
    # RAYGUN_PASSWORD
    - secure: "EfmwyVuqyg1KkB4Zdnm7GGBV9f7aBK2ZmKvDJH8avBhDCynyxCGh3aQ8gW1fpUdtEwA7J6d7ZY71SNugiPzCuhM/P9mUMrHXYvQ+ENun1RFRhVqYXx1f4LYNcN9nuOTWnpupdAmy13+qa/4tPorkCey3GwlqmB+n0Gx22gMGf2H/RqDQd0yApkffEdCjQiTFkTmqpNhW1Y9mqr6RoWsOYibOVT9Zh07l+yX17KzBkEzMYTCZrzRE45TP6dHPgN4faBAZS3L50K+VAJzqwPUecfsNHKufHvHj6CdniE9FdDZ1YtwQXY9HEzvJtyqLPogq+FWNJoiQgQqZZtkJctRX07jcL0GZIOsrirIlfAln8Kh+lcAa0cqpOERvxxBE2m+y97JzAak2gFEYMt9x6nfQKemr8ILJX83VgOG22/OgXls1gSR2VnBag6rjR0foXNwKmjX7HDnRLGO+bwzvthtcHjgOE1b7jLl/3YrBNFxuy+XY/jOSJSVBRGwBCBBSNZZRfY8XwMOgaIvuR3P7dJ+QHUzBjkO1JI05yQhTcp9aXfud2MevhZNDwfCNjoemy2b5JUPyKP1/dnBttm0fOmXu+2bk7nmz0XKm0bsQQ94aL3bq6fg5J8nSafX8L4K5LacovUHt/i1H90fvuMuSZ7uhg+cEmSj6VrclA4qFwL6cvtk="
    # JENKINSBOT_URL
    - secure: "n1p80/4Lu1sc+0xU26DPVm7y7KQcRsaq5MYGv5LYiqhw/1QAZeCfnAf/qAejwagvFLWr/eHM3wRnsuSzWNpJEo2nOmQZvgUIQu/2XuMUY2Too8B5jb2BEHjS7Awl7YFlJfcnb0exA0CHJJcQNe0tMhjdVjh9MMuwz1ZPcrjMt1LNSZthDb4PbZ6g3vbulP3cPgE5upzPUAz4q45cMZRKqJE3Qv0RGpiLpROzT/BJYvEQmGU028aMTWqvZZ+Vtd0OMb9LITS0iUGWb1w6Uw7xn7+rISSJIpz49LG9xwBctzdx7tI9WEPrtmTYzCnbf6tSF50EtYiC/s/qAcHeSio4oVEfPoHWfZWvx5sGJ8LQm/i7zO7iKYOdKHbezq57oFmhBPWsfm5uttyemhYgB2GcGqVfTiSK/VTIkt+oaW42XnJSlLHUHHcjwaiHxh6rjm8pSjYF35HOsuyb5Bye7i5v7r2LB42b4zV7xvKX1xbjtpd05KK5Z7JxDQLqG2E1NcC6T4rWpCNk0F4v6EXJkOOTQrO5bpDTAWIx3y6KNOhIiHhMg+/HijRQC4K9Aij5PBmjQTHITjCgtSbOEFN0k9NmXoaWDBysb1znycHRMDhV5AVNwOZwD7njSnLzH09jOiFO6F0s3tDIyH2wYMtMwoZTNm1p8fc7Ol7hK0WbqPrTFYE="
    # JENKINSBOT_SECRET_FOR_RELEASES
    - secure: "ZWdQoX/xpW4bPxTfGKmzoN3EZt1udd2ewOwOL27jUPJshOeIKjHYSucKKR6+YK3UkSOf4dEree+hI6zY8WQB6Ohou8Xh1Dj07fTMYQjtHxlwsqgswAuDYB6lZABxd1t8sjlMz+F61XPcxtni6Z3U6GObugRqmL1v7WMK2WlR0exeBlmMaG5S3w8ZDOk0444gzdJvFhJYxpKQjiCe095nT/y3IfPgz85LH/CyZTjGSy+aIVC5GvIUjeSRkRdPtkOmcUJIr+kXNxqiP8vD0uTXK5jLQOY9u2PYuo8p5J10As9mlTeWPetIdLVZVvRYCGMtQXjmfwJYo/Jqm+WvKXYCB/5jSAKPafXH34J/1K+AxRA7wyHdgPg/xQUCRRU2Q9QCC7WxJ5Yc2LPVsUsPilbeZCnbq1c8ICGdlv260wLZU5lH5Q3/K2dyiKMjJsQmr8d6rxgd0EtRiSizW/XLa4uyU5ZVOjuTuj7UUO9mmCnqo/+ZJqTP/G/dNJetD9yjHp0cH6MJwGNwZnsWzhQglB5bB7iLDttJDcCbirdzUC6vjpDOYH32Sscp36BJRDfxmwfyxYcUWTcIIthZ4s1drDI1YAzlWkhfjWy2APawDtXOv8GHWhGjNvn1mf39YpYIszUsvJ22hB14+o/4Xw7uq8GsLNA6zxnJsdfUENGBROWJLO8="

# https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-with-the-APT-Addon
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - 6

# https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
cache:
  yarn: true
  directories:
    - bower_components
    - node_modules

# http://docs.travis-ci.com/user/gui-and-headless-browsers
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email: false

# http://docs.travis-ci.com/user/deployment/
before_deploy:
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then yarn run deploy-travis-dev; fi
  - if [ "$TRAVIS_BRANCH" == "staging" ]; then yarn run deploy-travis-staging; fi
  - if [ "$TRAVIS_BRANCH" == "prod" ]; then yarn run deploy-travis-prod || { echo 'contents of npm-debug.log:' && cat /home/travis/build/wireapp/wire-webapp/npm-debug.log && exit 1; } fi

# https://github.com/travis-ci/dpl#elastic-beanstalk
deploy:
  # https://wire-webapp-dev.zinfra.io/
  - provider: elasticbeanstalk
    edge: true
    skip_cleanup: true
    zip-file: 'aws/s3/ebs.zip'
    access-key-id:
      secure: MpVUBkrtmIPqYLzrsYisYsE/UnOFU6q0ufgfWNBxHAFm/mDST9v+Kk1ZvhNKYskgMzJllQJBBqiRn05Fegam+DQ0oclbPr7Eg4mQrPbsrLIsc2qEpqw3fk8bqOssnHkKe1wlz7ihW3eQ78zOgsS/w95Zyd7wWiDzz8s7KvRPN8DLRGu2ksDdkPfM6RCbs9qsdSA5k8+DhZRXZCL/IHalE3plqOOJgCgTq9kzMRvxnFnVy0tLGzWQJvGOLYpjRwaAoqoLK7AX+WLfMSnBn+MuWCGmqPdk9Xto4cJnC5toASjNtu/bGYWuy4ShpzTivuwioJbxt5JGiq78j/MVu/5oBjzosJlSpNlY5++wrkLvfpkWMuJSC3/V40LkpLa+XF/MP18Bpbi44GmLTOCq4wJ/WRrYMAt4yQWURNJAv9tKqLyqgJ47HLBMEYABWUdr81apZm3ZKbqqmyu4GLclc7ivnVBjfmf5oDxMDUqp8owQO9YOsUX9t8Rw9XiPdasjx5EQ+EcvoAyBCPV6qlnFi7pj7wWnxu1DNhzxeW70BKhXizYwcBqSlvX88pbgCxc273Id0dAilrCgvD0/B2mvLPIVbJsscMyykjC7ZZOaznhfHQqeu/fXdfcVawVt+annovbFOWxjX5232ghbq12ux6qZ+2GNziW9vtEJeitPZ3XRPMc=
    secret-access-key:
      secure: aCiIP0To/YPm9E3G/q/JIHASRN0b69R23w8WYovmMsBFHddh0MBXnhh+Kf5Cuos+NdVatNs7mAqulLdmBF8TZhreEhLOd9PppEXPVXJrlvdDKejX3S6czUWD8tb4fSE4/qF9H8XYVa+Aznn/2Vlu3fFggAcAMv8lm7igTNb8rc2YZkaByNvwDjauoB1CwgvMsJiptDNy/m9EOJST9RqS/SDAFsPEFQLih0BRWbSYnEZ6yYtQ7T+ROOjjBxTefqf9E6s6PuXI9zrDzGtKE3mwibASts5lfVcKWBp/m1Droog7QxRgixUo9CoE4bK3tcSqpgBx/Mn1RL43C8pt2n2yxeXr6Rl1rdnpvVmz/7XbQqBtbX+atot63PKW4fuTlwCmnQfBWwsAqUZmnCHs0EgcFQR6VoO1D5FLKAWOFeo4RBCQ3mOr/kU3wTG0OrDVf3C1VpTD8W07AVIwcYm/jOSPJYgWwDk+OPz0f8UYbJTe8UO14LU/Wy6QT81cjEwjXJdCcv6IZS50iDNq9PxaACoOqAmfDZNwxuQBxN0kR1eWEobE+zucIfpa6OteA980X22xQIimPcVmmBcDjYce//o/12UNKZprUXeUqSPJsXWw8p3CIbJP8lI35aiTR3kjOG7XBG0QO1HyBHKudZHPGo3RU6dXVegu6POujy+oxbkQNyo=
    region: eu-west-1
    app: Webapp
    env: wire-webapp-dev
    bucket_name: wire-webapp
    on:
      repo: wireapp/wire-webapp
      branch: dev

  # https://wire-webapp-staging.zinfra.io/
  - provider: elasticbeanstalk
    edge: true
    skip_cleanup: true
    zip-file: 'aws/s3/ebs.zip'
    access-key-id:
      secure: MpVUBkrtmIPqYLzrsYisYsE/UnOFU6q0ufgfWNBxHAFm/mDST9v+Kk1ZvhNKYskgMzJllQJBBqiRn05Fegam+DQ0oclbPr7Eg4mQrPbsrLIsc2qEpqw3fk8bqOssnHkKe1wlz7ihW3eQ78zOgsS/w95Zyd7wWiDzz8s7KvRPN8DLRGu2ksDdkPfM6RCbs9qsdSA5k8+DhZRXZCL/IHalE3plqOOJgCgTq9kzMRvxnFnVy0tLGzWQJvGOLYpjRwaAoqoLK7AX+WLfMSnBn+MuWCGmqPdk9Xto4cJnC5toASjNtu/bGYWuy4ShpzTivuwioJbxt5JGiq78j/MVu/5oBjzosJlSpNlY5++wrkLvfpkWMuJSC3/V40LkpLa+XF/MP18Bpbi44GmLTOCq4wJ/WRrYMAt4yQWURNJAv9tKqLyqgJ47HLBMEYABWUdr81apZm3ZKbqqmyu4GLclc7ivnVBjfmf5oDxMDUqp8owQO9YOsUX9t8Rw9XiPdasjx5EQ+EcvoAyBCPV6qlnFi7pj7wWnxu1DNhzxeW70BKhXizYwcBqSlvX88pbgCxc273Id0dAilrCgvD0/B2mvLPIVbJsscMyykjC7ZZOaznhfHQqeu/fXdfcVawVt+annovbFOWxjX5232ghbq12ux6qZ+2GNziW9vtEJeitPZ3XRPMc=
    secret-access-key:
      secure: aCiIP0To/YPm9E3G/q/JIHASRN0b69R23w8WYovmMsBFHddh0MBXnhh+Kf5Cuos+NdVatNs7mAqulLdmBF8TZhreEhLOd9PppEXPVXJrlvdDKejX3S6czUWD8tb4fSE4/qF9H8XYVa+Aznn/2Vlu3fFggAcAMv8lm7igTNb8rc2YZkaByNvwDjauoB1CwgvMsJiptDNy/m9EOJST9RqS/SDAFsPEFQLih0BRWbSYnEZ6yYtQ7T+ROOjjBxTefqf9E6s6PuXI9zrDzGtKE3mwibASts5lfVcKWBp/m1Droog7QxRgixUo9CoE4bK3tcSqpgBx/Mn1RL43C8pt2n2yxeXr6Rl1rdnpvVmz/7XbQqBtbX+atot63PKW4fuTlwCmnQfBWwsAqUZmnCHs0EgcFQR6VoO1D5FLKAWOFeo4RBCQ3mOr/kU3wTG0OrDVf3C1VpTD8W07AVIwcYm/jOSPJYgWwDk+OPz0f8UYbJTe8UO14LU/Wy6QT81cjEwjXJdCcv6IZS50iDNq9PxaACoOqAmfDZNwxuQBxN0kR1eWEobE+zucIfpa6OteA980X22xQIimPcVmmBcDjYce//o/12UNKZprUXeUqSPJsXWw8p3CIbJP8lI35aiTR3kjOG7XBG0QO1HyBHKudZHPGo3RU6dXVegu6POujy+oxbkQNyo=
    region: eu-west-1
    app: Webapp
    env: wire-webapp-staging
    bucket_name: wire-webapp
    on:
      repo: wireapp/wire-webapp
      branch: staging

  # https://wire-webapp-prod-next.wire.com/
  - provider: elasticbeanstalk
    edge: true
    skip_cleanup: true
    zip-file: 'aws/s3/ebs.zip'
    access-key-id:
      secure: MpVUBkrtmIPqYLzrsYisYsE/UnOFU6q0ufgfWNBxHAFm/mDST9v+Kk1ZvhNKYskgMzJllQJBBqiRn05Fegam+DQ0oclbPr7Eg4mQrPbsrLIsc2qEpqw3fk8bqOssnHkKe1wlz7ihW3eQ78zOgsS/w95Zyd7wWiDzz8s7KvRPN8DLRGu2ksDdkPfM6RCbs9qsdSA5k8+DhZRXZCL/IHalE3plqOOJgCgTq9kzMRvxnFnVy0tLGzWQJvGOLYpjRwaAoqoLK7AX+WLfMSnBn+MuWCGmqPdk9Xto4cJnC5toASjNtu/bGYWuy4ShpzTivuwioJbxt5JGiq78j/MVu/5oBjzosJlSpNlY5++wrkLvfpkWMuJSC3/V40LkpLa+XF/MP18Bpbi44GmLTOCq4wJ/WRrYMAt4yQWURNJAv9tKqLyqgJ47HLBMEYABWUdr81apZm3ZKbqqmyu4GLclc7ivnVBjfmf5oDxMDUqp8owQO9YOsUX9t8Rw9XiPdasjx5EQ+EcvoAyBCPV6qlnFi7pj7wWnxu1DNhzxeW70BKhXizYwcBqSlvX88pbgCxc273Id0dAilrCgvD0/B2mvLPIVbJsscMyykjC7ZZOaznhfHQqeu/fXdfcVawVt+annovbFOWxjX5232ghbq12ux6qZ+2GNziW9vtEJeitPZ3XRPMc=
    secret-access-key:
      secure: aCiIP0To/YPm9E3G/q/JIHASRN0b69R23w8WYovmMsBFHddh0MBXnhh+Kf5Cuos+NdVatNs7mAqulLdmBF8TZhreEhLOd9PppEXPVXJrlvdDKejX3S6czUWD8tb4fSE4/qF9H8XYVa+Aznn/2Vlu3fFggAcAMv8lm7igTNb8rc2YZkaByNvwDjauoB1CwgvMsJiptDNy/m9EOJST9RqS/SDAFsPEFQLih0BRWbSYnEZ6yYtQ7T+ROOjjBxTefqf9E6s6PuXI9zrDzGtKE3mwibASts5lfVcKWBp/m1Droog7QxRgixUo9CoE4bK3tcSqpgBx/Mn1RL43C8pt2n2yxeXr6Rl1rdnpvVmz/7XbQqBtbX+atot63PKW4fuTlwCmnQfBWwsAqUZmnCHs0EgcFQR6VoO1D5FLKAWOFeo4RBCQ3mOr/kU3wTG0OrDVf3C1VpTD8W07AVIwcYm/jOSPJYgWwDk+OPz0f8UYbJTe8UO14LU/Wy6QT81cjEwjXJdCcv6IZS50iDNq9PxaACoOqAmfDZNwxuQBxN0kR1eWEobE+zucIfpa6OteA980X22xQIimPcVmmBcDjYce//o/12UNKZprUXeUqSPJsXWw8p3CIbJP8lI35aiTR3kjOG7XBG0QO1HyBHKudZHPGo3RU6dXVegu6POujy+oxbkQNyo=
    region: eu-west-1
    app: Webapp
    env: wire-webapp-prod-next
    bucket_name: wire-webapp
    on:
      repo: wireapp/wire-webapp
      branch: prod

after_deploy:
  - chmod ugo+x ./bin/deployment_notification.sh
  - ./bin/deployment_notification.sh
